### ISSUE TITLE
Pull request links not valid for on-premises Azure DevOps Server

### ISSUE THREAD

**Issue by johngraumann** [Mimeo/VSTSExtension-ActivePullRequests#66]
The latest version of the extension works great on Azure DevOps Server except for one thing: the URL for pull requests go to hosted Azure DevOps instead of our local on-premises Azure DevOps server. This makes the extension frustratingly unusable. We love the other features, and this is the only thing preventing us from deploying it.

**Comment by sand-head** [comment]
I'm investigating this currently, and I think I should have a fix ready for a pull request on the earlier side of this weekend. I'm not currently 100% sure if it will fix on-prem issues yet, but I've tested it using the legacy and new primary URLs in Azure DevOps Services, and it works as intended. I'll stand up a quick AZDO Server instance to check it out there.

**Comment by nshenoy** [comment]
@johngraumann Have you had a chance to try this out? Let us know if this is still an issue.

**Comment by johngraumann** [comment]
The last update in the marketplace for this extension was in August, so I haven't been able to test the fix yet.

**Comment by joachimcarrein** [comment]
Just installed the extension, but also having the same issue

**Comment by modestotech** [comment]
I've seen that this is fixed in PR #67. When will it be merged into production?

**Comment by sand-head** [comment]
I apologize for not merging this in sooner, I have been otherwise pre-occupied by classes this semester. I have merged #67 and I have also pushed it live in version 1.1.6.

@johngraumann @joachimcarrein @modestotech could any of you confirm or deny that this resolved your issue?

**Comment by joachimcarrein** [comment]
Hi @sand-head I just checked on our devops and the links are now indeed pointing to our onprem dns name. However, the TFS part is missing in the url:
https://devops.company.com/tfs/Collection/Project

Currently the url looks as follows:
https://devops.company.com/Collection/Project

**Comment by johngraumann** [comment]
I am seeing the same.

________________________________

**Comment by dekkermg** [comment]
We work in DevOps, not on prem, but the links don't work for us either. The links include our organization before the project. This link does not work:
https://myOrg.visualstudio.com/MyOrg/myProject/_git/myRepo/pullRequest/34

if you remove the second occurrence of MyOrg it works:
https://myOrg.visualstudio.com/myProject/_git/myRepo/pullRequest/34

**Comment by dekkermg** [comment]
Links are working again for us, fixed by #73

**Comment by sand-head** [comment]
@dekkermg glad to hear it resolved your issue, and thanks for using our extension!

I have an idea on how to resolve the hard reliance on Microsoft URLs, though it doesn't wow me. I could continue grabbing the referrer URL like I added recently, but I could instead split the URL path at the project name and form the base URL that way. if I don't think of a better solution, I'll attempt to get that fix out tomorrow. I apologize for the wait.

**Comment by sand-head** [comment]
@johngraumann @joachimcarrein @modestotech pushing the fix I described above in version 1.1.9 now, please let me know if you continue to encounter this issue

**Comment by johngraumann** [comment]
Still doesn't work for us. It is missing the **tfs**.

What we are getting:
https://server/collection/project/_git/application/pullRequest/656

What we need:
https://server/**tfs/**collection/project/_git/application/pullRequest/656

**Comment by modestotech** [comment]
Not working here either.

We get:
https://devops.inyett.se/collection/_git/application/pullRequest/141

We need:
https://devops.inyett.se/collection/project/_git/SE_Web_Flux/pullRequest/141

**Comment by sand-head** [comment]
okay, I'm pushing out an update (1.1.10) as I type, which makes some more changes to how the base URL is obtained. please let me know if you're still encountering this issue, and make sure you're on the latest version by checking the console logs. I also added a console log that displays the base URL; it'd also help if you could send me a censored version of what it thinks the base URL is if it isn't correct. thank you so much for your continued patience, hopefully we can get this issue closed out soon 🤞

**Comment by johngraumann** [comment]
Everything is working on this end!

**Comment by modestotech** [comment]
I can't get mine to update from 1.1.9. The last applied update was from Saturday.

According to Marketplace the most recent version is 1.1.9:
![image](https://user-images.githubusercontent.com/31730051/72874721-f34ec780-3cf2-11ea-9ad7-cd4ddf19d826.png)

I've googled around for a way to force update through the interface, but no luck. Either way, it still doesn't work.

**Comment by joachimcarrein** [comment]
Everything is ok on our end now. Thanks!

**Comment by sand-head** [comment]
@johngraumann @joachimcarrein very glad to hear links are finally working for you both! thanks for being patient and for your assistance getting this fixed!

@modestotech have you tried uninstalling and reinstalling the extension? that's one of the ways I've seen people "force update" the extension in the past. I wish I could help further, but at this point, it appears to be an issue regarding the marketplace itself and is out of my control. as this issue appears to be resolved, I'm going to close it, but if you get the extension to update and find that it still does not work for you, feel free to reply here and I can re-open the issue if necessary.

**Comment by modestotech** [comment]
@sand-head, today the update has been applied and now the links works great.
Thanks for your extension and effort! It really makes a difference for our team.

**Comment by johngraumann** [comment]
Was there a regression here lately? Seems broken again in the latest version. It is missing the /tfs before the organization name.

**Comment by benjcolombo** [comment]
Hello, I agree with @johngraumann as it does not work properly anymore in Azure DevOps Server. 
Strangely enough, it seems to work for some users but the "/tfs" is missing before organisation name for others. 

I use the last available version of the extension (v1.1.10) and users that reported the issue tested it with chrome. They are connected to the same network as the server using eVPN but I do not think that it is related. 

Edit: It seems to occur on Chrome but not on Firefox.
